spring.application.name=springboot-template

spring.datasource.url=jdbc:postgresql://localhost:5433/templatedb
spring.datasource.username=${DB_USER:template_user}
spring.datasource.password=${DB_PASSWORD:template_pass}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true

management.endpoints.web.exposure.include=health,info